### PR TITLE
Promise.race accepts an array

### PR DESCRIPTION
**Pull request by moodysalem**
Promise.race accepts an array

### CODE REVIEW

**Comment by makoto** [comment]
Hello, I deployed your version at https://brave-creature.surge.sh but https://myethvault.com/browse#brave-creature.surge.sh returns blank page

**Comment by moodysalem** [comment]
I’m not sure why, I just tried that URL in chrome and it worked. Can you see any errors in your console log? What browser are you using?

**Comment by moodysalem** [comment]
I was able to purchase an ENS domain using myethvault.com via that deployed version
image

**Comment by makoto** [comment]
Ah I know why. Because I was browsing from the browsers (Brave) where Metamask is installed. I checked from Firefox which didn't have any extension and seems working fine.

**Pull request merged**
